### ISSUE TITLE
What Perl version should exercises target?

### ISSUE THREAD

**Issue by darksuji** [exercism/perl5#92]
There's no explicit requirement in the existing code, but I feel that we should document the versions that the provided tests are expected to run on.  I don't favor writing extremely backwards-compatible code; I'd rather that the tests be fairly decent models of what Perl should look like.  To that end, I'd like to say that the test scripts don't need to run on Perls before 5.10.0.  If they do, great, but don't make me write `my $y = defined $x ? $x : '';`.  I think that 5.10 gives us the best balance.

But I'm only one (opinionated) guy, so if there's other opinions on the subject I'd like us to discuss them.  If it so happens that no other preferences emerge, I'll update the README to reflect this expectation.

**Comment by yanick** [comment]
(all the following being IMHO)

Perl 5.10 should be the bare minimum. Considering that 5.14 was released in 2011, 5 years ago, I don't consider it to be that insane either, considering that we're talking programming exercises and not, say, migrating a huge infrastructure. 

Personally, I'd even go up to 5.20, which introduce very nice features like signatures, but since we're talking baseline version, and exorcists can use anything above and beyond that for their solutions, 5.14 is already a good start.

**Comment by xsawyerx** [comment]
(Under the Humble Opinion Clause provided by @yanick above...)

While the Perl 5 language is available on most *nix operating systems, much of it is because it is used as a system language. While it is convenient to not have to install it, using what is viewed as a system language (by this I mean the instance that is installed by default) introduces some constraints on the user's freedom such as only having older versions (the language interpreter, as well as plugins) and requiring to install modules via the system's package manager (if one exists).

I think that nowadays with projects like Homebrew, [Perlbrew](http://perlbrew.pl), [Strawberry Perl](http://strawberryperl.com/), and [ActivePerl](http://www.activestate.com/activeperl), suggesting the user installs a new version (as they might install other languages) in order to enjoy updated syntax and new, supported versions, is not unreasonable.

This in turn allows Exercism to focus on shiny syntax that provides a more appealing language (as it is now and not 5 or 10 or 20 years ago), sparking more interest in the language and satisfaction in the work.

A beginning section, exploring how to install the latest version for popular operating systems, sounds to me like a worthy introduction, helping users set up an environment on which they can enjoy developing - but that is not me to decide, only to raise a suggestion.

**Comment by yanick** [comment]
To have a baseline to compare to, what is the NodeJS version supported?

**Comment by yanick** [comment]
(answering my own question) The EcmaScript tracks uses ECMAScript 2015. 
The  Go track supports 1.2 (2013)

Perl 5.20 is from 2014, which doesn't seem that bad.

**Comment by kotp** [comment]
I think this has been answered now, with the bump to 5.14 minimum from #159
